export const DUMMY_PLACES = [
  {
    _id: "demo1",
    name: "Tatvan Sahil Kafe",
    description: "Van Gölü kenarında huzurlu bir kafe, Nemrut Krater Gölü manzarasına yakın.",
    category: "kahve",
    location: { type: "Point", coordinates: [42.2815, 38.5065] },
    address: { street: "Sahil Yolu", district: "Tatvan", city: "Bitlis" },
    priceLevel: 2,
    amenities: ["wifi", "bahce"],
    averageRating: 4.5,
    totalReviews: 142,
    distanceKm: 0.8,
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80"
  },
  {
    _id: "demo2",
    name: "Café Nemrut",
    description: "Modern dekorasyonuyla Tatvan'ın en popüler çalışma ve buluşma noktası.",
    category: "kahve",
    location: { type: "Point", coordinates: [42.2780, 38.5070] },
    address: { street: "Cumhuriyet Cad.", district: "Tatvan", city: "Bitlis" },
    priceLevel: 3,
    amenities: ["wifi", "priz", "calisma-alani"],
    averageRating: 4.6,
    totalReviews: 95,
    distanceKm: 1.2,
    image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&w=800&q=80"
  },
  {
    _id: "demo3",
    name: "Göl Manzara Restaurant",
    description: "Van Gölü'nün muhteşem manzarasında yöresel lezzetler.",
    category: "restoran",
    location: { type: "Point", coordinates: [42.2790, 38.5030] },
    address: { street: "Göl Yolu", district: "Tatvan", city: "Bitlis" },
    priceLevel: 3,
    amenities: ["wifi", "bahce", "manzara"],
    averageRating: 4.7,
    totalReviews: 210,
    distanceKm: 2.1,
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80"
  },
  {
    _id: "demo4",
    name: "Tatvan Büryan Sofrası",
    description: "Bitlis'in ünlü büryan kebabını en otantik haliyle sunan mekan.",
    category: "restoran",
    location: { type: "Point", coordinates: [42.2810, 38.5055] },
    address: { street: "Çarşı Mah.", district: "Tatvan", city: "Bitlis" },
    priceLevel: 2,
    amenities: [],
    averageRating: 4.9,
    totalReviews: 420,
    distanceKm: 0.5,
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80"
  },
  {
    _id: "demo5",
    name: "Bitlis Tatlıcısı",
    description: "Yöresel Bitlis tatlıları ve dondurma.",
    category: "tatli",
    location: { type: "Point", coordinates: [42.2825, 38.5040] },
    address: { street: "Atatürk Cad.", district: "Tatvan", city: "Bitlis" },
    priceLevel: 2,
    amenities: [],
    averageRating: 4.8,
    totalReviews: 320,
    distanceKm: 1.5,
    image: "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=800&q=80"
  },
  {
    _id: "demo6",
    name: "Ahlat Yolu Kebapçısı",
    description: "Odun ateşinde hazırlanan kebaplar ve taze pide.",
    category: "restoran",
    location: { type: "Point", coordinates: [42.2805, 38.5025] },
    address: { street: "Ahlat Yolu", district: "Tatvan", city: "Bitlis" },
    priceLevel: 2,
    amenities: ["bahce"],
    averageRating: 4.7,
    totalReviews: 290,
    distanceKm: 3.2,
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80"
  }
];
